# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c
sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget r-cran-knitr r-cran-rmarkdown
#  - ./travis-tool.sh install_r rbenchmark microbenchmark

script: ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change

